package shane.leetcode.problems.xhard;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Not my solution
 */
public class Q3337TotalCharactersInStringAfterTransformationsII3 {

    @Test
    public void test() {
        assertThat(lengthAfterTransformations("abcyy", 2, List.of(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2))).isEqualTo(7);
        assertThat(lengthAfterTransformations("azbk", 1, List.of(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2))).isEqualTo(8);
    }

    @Test
    public void tle() {
        assertThat(lengthAfterTransformations("x", 16, List.of(6, 6, 8, 1, 9, 9, 10, 3, 9, 4, 8, 5, 2, 8, 10, 2, 6, 8, 2, 3, 3, 7, 2, 6, 4, 2))).isEqualTo(417796858);
    }

    @Test
    public void test2() {
        assertThat(lengthAfterTransformations("uc", 16, List.of(5, 3, 1, 6, 4, 9, 6, 6, 7, 3, 10, 6, 8, 4, 1, 5, 3, 5, 5, 2, 10, 7, 6, 6, 5, 10))).isEqualTo(383229144);
    }

    @Test
    public void mle() {
        assertThat(lengthAfterTransformations("bvqbowlhpfhpaddcegzxiawnprkhbvqlmqegsydbykdrxywxvtjlqkuvzasrfdwgepgkbcsxebrkeegttxugleyzytnfpsjimuxqjpjgqbxtbrpntxgxaahldwwnemzwtpgnbvhqikibmqwkxjlvklnuidgwhrxdnwjzxgazfckirtzzwacsvinisjzjyaibwamcbjkcxkdzripdrgyeewkpgofezpcbjbpbdhzltzmqffaqrqcefjwyuyimzpftumzdkazbkijezidrcabvfiltkxzzyywxogsccxkmihqwmehuicpolzxxqvyjdtsuohwthzmigprfjooframjuckvqxjboowpmbdwokzprniwejbbbzwvspufgilhylgukfqgdkiuezvfhxsbpkorbouyqapbwlbezukjhbiiykncopskkzajggslrplccqqcnogvhzjprfyuanmuuwhbndkmasesrpgwdgjyvcscmtiwyhsexvahitchwswafbftffrfpnwepijdmxlzihsnszpjvztxjvxbcbepbfhzcvmxfdibhycvzmzsnqtowvnyqoprmlpfdemyxawlahnlyihrkauraudjvkbsovqhpfvuxletqienvlcwnwdntusvwrgmlaibacdmxwarakxiqiqaaihtnfdmkrtknqrhhsebeizjwrdavzldafamwkjvtavitzoyzwavorvcbclapuzeeigndagdbpbxnexumoshtbkzlhsqetyzqfhswuxnxtrmzjaxlzjsdmdhgpjtdoogehkcanyylfsgpceosbeokdzarlogagljrzadttgwaksswbakodwjtpysrhthgmlpjixcxrfgaqcnqlchanwivxngtorsrplqmrxmaqwairjmbepggtuajfmqtbrcgczlogwkrjzhiqdbqbrcrlpovgspnmuxdqewqlbhzchfxrcxblhoozxmasnmzelzzfclsklpxexzmnenoigazshmhwkfrlkbkyerupbgedosfmvdburuqfydstnjyjpmusnfokoyjvdgnphvotckwvageasfrsknnxnbvmqqlvtyvbgijndosppsfrbzmkkgzzufzecmyqnacfyuylrewbuybecszxxovsflslzbbpapzywgahkqohvlzdgeveoqjvawwehecdlgtnseubafazduxgwbxqzponpizvsjosjddwajtpvenwbsgtqtessiacspjiehlqvjhugextkjlhgfkqiseqjhfvkewugmmwksrlxrvnrmstlklaytbqwfvzaebkbwjsqfgvwdoorepxcxbelvaobjgtdjlvqyninoehfroviegdyiilrpewvgpdipfqlizzxzzfvhqizrdcgmpbjffljpzyljupwenvybbvcgwvgqnfcfdfjlckioxkwnqiurpodtduitawsinvtbfnhbmozwukjqapeewivqmtjuqtlwygzfujfovvabmwsmmousfvcmoedejhurbxrzbdrreqymtuqzyjojjncibhelurkwajdfvdmeiabxfaqqpiqishborzzkztsfskfbbqwwathksdbrvzfbncxkmretflmddtoyxthwibtfeeowiippwoccnmpcswoqstmjdesxkhriqhftdojbsghfudrutzgduxdnrrheksjdyzrdtbkdbcrjkfhlfkvuadhiqbpnqljrqprdwmthcgstakkrmhivuirdvmwqkswjgnmqcqziwqbqxhrhhbtgagbdibjilhzuhglolxwpfywltxqfvbbvkmgpasvxaforlbgkttrnmhszehynywnwbxkshrajhymvgexcsqcfmnhiyikmzkwxtwaebajwoxeqmehyqrxyairhlsbazvkdbqhebtovualatufvauqeczcrrkyletfobzjvcauvnunnzogkdznfwstrkoicafynnbbdlutkeauqwyhqrdkgtrdbngeljgdfrvfiiampsuawxpsoosedtnnjwtdkwoykbukipvsvyefwkmlkrezsglrjnvafyyvbirnjkqgcobuhnwumbjwuyuoluyjmihghzlbrkkjewnobcuwopkdvokmqqwkpesgkgqowcxglywloojdjfhzeoihselaabpghovbwgaxwpdonuthapdunjpqldjkzovybxpzomvviutgljkpbdimbmanzyyzghlnwohqpjxupzrrhcrqzqhiupkinhjoniwoyxlgadvdlqnfwjucdcvvzmezbsqtcotbrmmjtlaihilpccrpszratqghwktpzciqexyqrbxnzfjbevsucqhmaaaedekipvhlbpscrwjwkzyodhssywlikjfmdbceehcvrhkdjxtvgtqmomaraninjzhvwzdteirgubbpochqocexfqxnqmqngezpedgpsiltsramrukxshrfhnuvsxafjfgkmqyapytiaeujczucwceyecjjbgbdmoavohqovlsunwbglroncvekqqbkuijehjbnyteoaegycbygfkfekkqnqcrktbbaksrcgyqmqnrttmhpefhzlmvoajypyrdchmyibgfbjgumrdfchliqdjjmoztvchtdzckjyzwyvfvabscxgymxosfstoagmvpvdofemlfzfkvexwrphbfxfsgumjvkisvvrpjztcxuhzqjwoatzqyiwjsvoismgadkxnejpbzhdymjbgejoboelmdpspqisukmzdytpqzbzpdhtyruutllgsipecruztupxjxnpgbcgtbhhkwcpcscjeebjzaxambflggzdhaupwjsswizkabaapecazfohbesowsyttexkqlayvnghvpcrhglqioufwxdhyqiyeedfioepddqmqzgvbvnkdbkkjujwrlfuxjfbuhicxnanjghbtnfdfxrcxdrqadmbpascwccifcpubjarrnzwtpglzowwekotstiwxlzyiesiqtbhoelbugxricrngzpxdarztndqnwtztoexcfsfffybkztsiwzarvzxesxrioahfheolpqneizdobicukwymgajilvdbxjbzzzqrjcoihgjlofofkxsbfmztousxolyfynxttrfhurvacvuqmvdmvdpvjefvwnmvcjqfleifbgntlwhynrqprngfcahzayyxrpunwtqmzczmigqpmmfyvvqciskpjxmimbdtttzfimioenelferxtcudmalkbqojuyrptrcrcgokjzromzeeyuznjprormpqtkjrzuwncumgrtpruqpvuiaseftkzhqdcywcovjytkvxkutknlymoiwknogudokqmwvmkqcxbyafpnmderopxihtuvtacnmkshhskozpysvfinvkseyhhdycmvcqmxaqbhbvzsdzlguqquqcabykcsqaeefmvgfmevsnukwrytcdxnmvpbfqekcjmccqfqswmotyxeezypgarndmalaagviyyenfruxcnwqtgyxifstfgbsdmlwtxmkoahobzemdrbwccufimsktsaluysyigwaveuezhfuqniciriejhwrgdzuvtducvkydelsfthgxizobpfciquywfqhhpsthfipenbotvizyqrvtfhkzvepscmfauhctmkhhyjjrmusjdwfuynghbwaorifkffnetqehbkapoqojkkubfxoisdouzqxejadzulqfquzmlaretcrrcjscjklfufuizrtvosthcecivbogxllpxzoihiirvderqkxhekqxaelgvippqonvwsifzoytfennzidgwmrppdlwwfcvuszmsmmqsftuhnauohniuftzbabhwdekllsszmloqjosdmptpuusnnzkrrxdyccjoxyoavkgdwbwkliaotzjlesbiahathesagnlrfezqorgyukasxnlnqlmcfokqztpcczlsvytwmrphmceyqtnvntwmmljfisyiszhacfyhrikvbkejblryhfgdwumwzstpzcgptphqmqqnfttuqjshcmmzfkopbqalbxjrscbefblkuhbzmnodgajzoqnkhzwsfhpvgokcyaqqybcwbqyrpdzqdtfiayvophivvfwgkigcqttxpigpqxvyvtfkmdgsdijxihcyiykdhxiyepcoxkpjirsdeezsjlogbguvshcasuvvpyrybcuvqbqtaddveyndsnrjdffszzhvknbsrcaeouyfqggpxzutgoxmkanvzkztnelncpxsjcimfoefqivpqrfvkgitwwwqtqisozoxuxheaumhntikfzlgvojnecympqdnbeghyktnzbbpcpfdqfnyihjchqtmgouwoevkylhzyxmmkoiywopdwfueznukqgxdxvgvqlxmptdszochifankbozlktpmstvllvkqytxywteiidxtvpdwurzuosonvmxjqgjteqmclsjxklopeiysjqjlkvabdqtmuvlalchllobcjxcxeicnvmgttkhxabkfxppktmptczytukbzmwymwmchawbohkqtajgiwbmlhvivmhdeeonngvcbgcsppbxeiooilgelxxuudkjxzzugcletjdtznqpzdalpzfhqzyrntljbnsbfpeeqvgpsrykunsmjjasnxmvmavuemnnvxcobjzvfvygzbdzyzrgxpqvarkwtlsbuiksjgsbhcneytfylsrokpcgjahljzfwusmlwydfhvqbjwdckzowqdhtgmtswsemghxhwlycaheudikfjfmpnuvfxrhfjjyeregrejcfcibtjjxnsyeohuhurrxyakklddbbruzxmjmbyhyrzqcjdazkvjdhebkfchywyqevqgpkwrfiwtssqvbzyovhaagqeekjcbzznziyymrlpbzclvttzwcpesswxvwknzpqdnzcfwwdanrvsgpfxakgchrkkguerurekcumuhlhoxhcddsvmxpnmkfddjcepsjnlxgqaqtmllpindndwwavcthnujkzfdkctnomipuctconyajkfvpwjjcwprzrzpjetmjwgumaxlriijkuanmqpuqlfofjdqxizbpdmphnavmsibtwsgpgtzqlxcldejedwigopiahgttqffdgyigxmmoinxjwsuljhtsjaifvcapgoxazoondpyvrdfodfqkuckyibcxykcxrzoxdxkwgjuafyshxaaofjxnftgjlswgtkbzyxxgawhrgliabdncnsfvmcuszkgtiogafcvtpssiqctlmaccvkqroobmnmirmtwhgcwxxuxghorsjauqkxjewjdbfamcgkakjlsryvawhsniuksmicjscbgcliccjrinjwtnghnecdpgjbkscuzrcvvdgigdrqmqocgwfxmosbpjwbjjafdnovgxhetphpydyogxuqyxxxqmyentbagcgfkufrbzqmzdljfhqxfdlrhvnavpouoeltrggaqvxaegboljjcladscdiddqihbzukbfcjgqahxlzvweqkokbpffhalieatflejpxstoseqossdrsbflrjolsksrboyewyxkvyodykugxinhgpcmqnzhlymvjmiybncvsvpvzldlytvhtqzocqugzvlrsuxnrkscscfvkpplovcikigyopogwojvwnxhguzxzrqjyduwpsojsimhogzhfmstjjyvsdnycpkjgynelbyszwddycgypflqkkobkyvxeccfcgixhoifxuehagwdkzztanhdivlsntppgcdajyyuhrtipsduanwkagmhcteousrweavrwqnncmxgdghjpcwjtaokhudyzxrxhnqwslgpoemjopsbjmuvtmfbyniuxskwuzdadvwueiohacxmfuddkkttddrqiiwsujeaeodbzguuddyzwnpycfknuojjdwayqyttpbsuqlyvbrgidmpzjnqbkagofrijikrittaxtiqqbwvtrnqutmzjfnqkashbdtisnfffihniknqeblchemzwsfhjoiotjmuolyprdfpidfpeutllwtavcdoreitatpdjififpfobnrhkowzjnbdoselynbewxagtzbetyriooufnpgjnzirjutvestaxbudtfwtlmhokedkuntejcyyzmhyeveyixyahwwmohmtuwvosqiiwokkyyiqdfiuqrylczllgbrmjpydskjblztygxgpeqfiikbsvrrmfmjjyjnmmcshmkhywnztmymcrsgpqmcvlypuydtrnyjxrlnjzkcwlzzvougctjsnzrdhqakyftwbybljakdsfmsexaxaxksvbqqvaegfestqfdsoaofaggyfhvkvhlvcbgtwdmnuwthivinencppqwxaojabpydxlcfblgysglnjoqkzywfwetjjshordjpfxawoupqpjtirmzylmpleuonnveqdtwzekqakrobsxbxqwildpuvkmlogtzzhwvuoztkspxekuvrqwzbzdzhjozqosnvmrucnspeorbrwlgbrqljqgmkuedgcjptzykyzmovpungwinhmrysehreebjtkafbglmrauhympjkarcyyldmzhkvjnkrtzdhhvtqoywsrbfiwswwzapmkbyewkbcujbyyxifbzigxsfoteelpywbjdfzvcnuwybbgndnbuenozmlpawibxklhgmcoodwipjettuhutambkyevapbhhumjhqfakarskfmjjpigrjsxlqhixovzdefqxymgnwcovfifjvubjaxoxtqmaidhtaqcsqggwxwjcsqqhlqysswpezaoarjssligvnccvbuejjbkwzxaikkcsrqmrdvmskgopzqlpxdouzuhsokcbweuwrzqcuqjxewhpmkrafivzurajyzlgsstlssdhfnjmjotyjqbnsjnfcvsptejrzicswkzvmhwumtprzhdxzqxjlnkgmociveqqrngydipsghrmntqymmqmwxrlovgxtepxfxlojwpmlzmenslyljtptkndyrjuikjrrurazgwgjginlfyuwmkogriokpxhbablkdwwnxxpjokfnlimmbeausuukteotoypwakqzeborvfwiolyvvxniukzwfzvubuvayzkhldwmbzpwjzmooryyxotosaaaecoivyqvqzqrylfdugcubmasktfpxpsvkqrqntipxlqpbjgpjootfvxbycvdolnrmcgvdkyjlyqjgozirijcwafdajnrokkubafhujulkfmqsewbllzqhkutsardfvkhswcpflausmcgjlhgskdsoppylvgulxvuquaehvssuoxfgqvidlmmocmbuhmzpmetmoewsokxpcnybnrmkpjxgebuydnftzxunbdmpqvttmpfziolhaoezdwhcrgsusxmgqgstwyojzwqtfnqvyjeihzpzjhzvhpffdnxejipduvvhwabolklhkgqoyqfupepibhjtnylnoivjfguohjlvtrxnjuqhhynebewhsmahwpqlpftmnvmjuaubcnunggqmwszhrhehpesvviafoxlmnvhdjcokoizxdtehtlxpucjyncistahijvmletwghdehijbxgqucdznemeexaxgkokqtpbhhlqxntxsflixprpwhkaubfiejpvcnavbopiezsfsdbaoeofrqzlneffagotrzvlkfwzlvncjglfcjxdxajggcqvceaobzdsmrcsrxjkxablpnmwodbvdwahnvsoxbiyayzerffyprleaurqqnuldoojygdufoqxgpnvdnwmbwllukunjtqxwyhsrqwwmtkgyclgbllxogtvjerxwhyrojvrulnklkixknnmgbmszxulhyykhhacfckkoplddkkbzaukxpdumdiodrswbomdlzdiifatlupwvlikgvhxczjfkrsuafrlorweihjgnpyuenavkpykgbavsfktiiqpclfuvtcotwztqprwjfimrsqocjpjditxjsueslhdduqrguwybzkchgiroqchlrosjwcjucfhhorckvcfoesztzthmxyeupmyrtkwsaoouhmzsufrtycbufjjsdqmmfkldqagajdmpyrwrfkvxgldmgojomwcinwhssttfxyrngqdeoqxucukowmskdmrsruegekxdbrnmhuegngcqxzvmoypplxqgsfivquhfnkxsxqnczhiuflwnmigstdnavsxvvvuvxzmjizyvybvqevjdklmmohsmywgjvonqreydevnioygjmzanipawurjotdvpkaevviyvvqpqrzydqygcazvrwugnzhhclaibjgsvwglzgxfaqrdmzqoblitmsbbjwfltnusrpyupgcbrrtbuqgxylnuobrldpzxirbgkbvsmhavdhmfbpbdzwqtqaqbezjovitosmgyatluomurdzchrtihtmoegzxppaworfoinixhytalzhhxlwvbgzujfgfwjldpwtzlzunobgylqrncyvzbsixbytwffodqjyxnofydjmtvnlmovvrfduguzfldsvwwcrmgtqsmjlfatxsfjzgxdxleowodnovisqywbwpufltlzjlayxkfiuvkztdiafjhudwsvnjitziacoeyysukccvnjyqwrltbbclnyagfjbnukqpdpltyiesbzhmueyrwpontbreoigznxdexiqbfbiietnisupsmvicxknbirlydwpyntpuwmsfmkrmpzrlcmgnddsvnmfisokxfuirptbyioexvinhnxbnkuyabirdgbksfwenrycvpijtlrgsipgzcdboiqucqsrotwceqoscccttorsboixxpbkvxefcwxqcndfwthnbfdqkagzxcgrtykccrtvjocomxksgfvaplxmnmqxpclduuvmbawppnngiotplzfevrenbqjsubzaelsqhvkditlmcrokwbbhvhwkjnbcbehwukixwapkxxnxfweqmjbwozdbgbjvrdjvcdywxsfkdidpybqyluwtulkiohtvcnmbiqkwaivoahykztaioxdptyzdvlyrqpqcyrvdxvarkgzavsmqsqoyrpgbaezlaizrcjqdvzdqtnlolkvivbnhdmgcxgsshwkutdtzybbaajaxfcgzuukfajnjlpppypbqokctsrakdnqpkrqmkriwjcuvohidahrtrhhwrvktnbkubvuarfbnicneqylpzztsrcyeixvbtrtulzmhrzgsyicqpuaygszlhjfrhoqmuuuokokfvkqwuybctjnnyjcaazswajpdrrzpdcshvvzdudclbtbmgnghbagcaetwolegcjunmhoejnwfpgcudwvqzatvwdjnmppdrwhfxivolidkqghlwhevqyeeanookdbmjjywvecepwmsjlymkwvpxspibxjzgyqowowiaisinfqfcppfnniaqxbuywulcqtgktssixggzbhdlxarsjygjocsjkxirhlcqjhlhgacuxxdmrqrcagyqxktpuryxyczeghsxsikqnvuwnttnjylzxobxiblesdlzsadasfiufvtvpihgfvupuxctmxgteszzorodcdfrvvgbxjljgbxpoaenoofvkyyltfipddwxinawdszinxaeevgdhtkndnifjnvfduhzxhgckayrljpzdaqdjebxhjglrtcbspmfyejytbumftarlqqywiquybqwjzgubkloqtuwekrkdvjvzxbzdawbapnduxrexmqffkpbmwrzmxpyftkooiuhzqzepvjfzpubfffluepcorcyaklidaiqggvyqiqdyhhrdisraftvmefzxrxukmdkzzevwowvvpixswrovgyuxrvqewspesfqxacajyqvsbnbfhbxuerjzvpmqvsxolfqsqxfmezfhqptnreuxfhnzxmgylfllzopvrlvsrghwcwpdihmtcfyyextjvzcxdfqtklifzdeusjbvounkthxxwhriutmroplcmtpsmbvcqzusejiciatpqsfxqqhunlksdfqvwbgrgezcvgpiqcmtgkuzqsejuihajgxlojeylpnfswwxbtawmtnujybesbdkbirnrdnjwmpmcufpupumfqfckvpoikmrhgcpigbnrraqceqttqxgawlkpngqvqclqbaznnyowgczpmctvpgyfromviulyojygqoswrwlrmzrpbcjeqnawaxqbolaqufbomrljaiafsfkrgpzszzskqmtcdhokteeuduvwlcnhdltalnrxihyjwyvdwtqxpgszygzcmnfcuwmqrdlxcfbyigayuwfgyxuddcdyrpinhihkboysyfnbgjveictgmiuaydbpikfhaxhwtqxhqxldxlopdheggjyrhfxyuibjxonbdrzdetzfqwdrbalnvtcjcmpvekxctqiceuztktyxdwpuokuuqmdjqzejwhmxtjfeukeaucyafoqkoirweonjjgvdqibqbgngdaamnivomhajsnronalruppsyxxfyeqjvfrtwbeusepthjiatatuqzrdlqepqflbbrvwqkoeaomviqedsphrabmxamxdbogptvarwfrvunitolfyjhmwebmtvwmshxmyfgctvkcziaojmqrzgpfunkvanhazchxlwkkzqkcygnrqnnsmenmyzwxouaalwxuwggbvyhdgijfwaqrrodreltjguejgsfppklwzirzsmalbdmcntrrfzvstsqiuzypgtowutqlphsovjxbuqhjmvtsztqfkfpntoztovadhyekpwcehrawhqafvucldevctklvjtextviyirtppkysjoqsgympgyvozrqiwfxzyrpresisbcskjhafhqzfflgaaiyxqwlwdggukkqjdwquynrjhfdudamhtetzgpcjcwtqmttdjyyfmbifjhugsijmkidrvhovvjkwhwqvzrdyzygbhjjueyzrdlfdcbhatvwtvnqpmnvfanjdydxwzcwvuptswhxvhivazcliiiykmvlhqbgqhveklurcwvrtalohuydnvmajexultfoqgxjmcorumsbutlbryilkrxgerhgccdzijpsyvwhvbduhnckozbsakpqlenptrigxeqqwqzzwqnjhyelztzlrursohxwhxfagxauzzywzdgtpdwbxndrxcvildtmftybitwlykbrvhpqwvwqdqzjbrwpbhxhopxzmjhwegbdclywaaidrguuzxthgntrkbxrbobterundhzddevsclkygaumdeafnfheumpzhvkiyaxkfpaikjzpiveukjhhptjvwppsexbyjvkbaiyvegbrzivzrpzpjrnfznjkonadraylahanfrscphmhzazpranzbyfzvrocnadbzpdmccvpkdqhfnblubmwapdgxvqwveocfbrfoarjkqyqwypfczlclzbnstwbfbmkcuvbbakhfhibytutpgxagvyvusvgtudhxtjkmgonjwlumqkbxpbnkmkmeeufpjcsdkkhfxadhykslduwchjjmmkrhzwhnvzrabtyqbisitowvpvmatbjykmozwlxqzzikzrivueboujhftrjlyqqytgarrfjjackuwtffilqzkmwpdcucccixafnydlicivadiwthsfehidckoexajvubqxeusfwqtebieoyvlrsmvttjmfidnktnjshvagpxclfudqpmoruenmsaipqsaoukmxoxdheasupjvagpznnjpkugvahlyokrgkpsaexlxjzjislhywlbpbtvtviiavgpclddnnpttyhrqixqojlwhialyfchlwzoeeaurrijftbmexifoolldnbdttnvuxmcjwgjgrxlehiporcmqfjasllvzykmcpkdbbcauyxmtbnwdzyzwzeidxncaqyorganedpxowjxcoyqbsuekkcavfggqbrfxgrcaqmelwodoxzirvwslonuqihdxyymrmewxufeqwfwhiulgznxfbmeimftsvcpotmtsynhfbqnknjwggwtqceviikbebcwcwqllfzcjiiosisbfrzilwynbvngahyljcckksktbqpgokiqinxaatckwvseihmbpofdqhrwmcclbnskfofydwtujiunlodasbvtmautgelnsephvuhmfcsxjndwzaupadwaertpxmqjvmzbnjeeyqgkttdjqgmbennhiudlxxzkqnomgytuntrmpzaqtfjqapbxmuenynknllhokuqclgspfxaicgqckvethhgvpkyusmeliulquhjzshgleuanttzvwlekvtwdqvvggwhgfwnkppagjbngfgbmxgogpkkkfhfdlbneemvvfhghuqtriovqtbylmzrwwhpsbxsstyqsuvkdvnvrrgsjmdqltznobotlqzocjaciecasgkjxbdwitbxhvledpcyjrytppduneivcaehsfpyrlirprgyeprslsizhyuzvzrqcxltyslydethcsercwgojhbrymzsvdldedhorubbhdoedksyaxkygpqaooofvgoqyziijimrivfmvpdpeawdykbxtstqfvnczgwjbvstairchhtczhcqlpkldczlhetflhdccuhkkfvbxfuomhaqbjsesqegwixwsidvzrmqadyortgxfxcqfgmxkspytkqfwvxrhlxudmmwrwmrbnutdjtzvjspcunxshcukgwjppaaewgtkrqatzjzkybhvpnuzncxzlncmbsccumqjgwwgrgufclsftqqqaszekqbivboitgnqmvekkqtrkrbzftargtjjbxsujhhxzhppilpoczgdwncudjfakdsmgvqtvcarxstftqqvibrepylsadrmavmjzksuhyfswkpiqeehrrrtsjwvveibpuuiqauvpsjzfphrrbrwqpufanqodrxcrycchzjgshvrmfvezxlpabswurgmybjsppasuwffibctmzrtzvjlegvtctgcudhrggiqfdzwivgzasbrckrqxztfmsavfnrabnwwkpwybyhrnxgecbdeelfhzoblwtpxzokxhnucwzemwuoqpmlxxzroejnbpyjweimvrwhksmvpaegzfriblojsfsughbsuahobhbiifnoamhacvjooocfwashsisuswrtflovjeqzwmgquimawljzplrqkqtsqhhnbnmzbyjeapuqbkbsxmlzzlfystovsvuadbbrwvwzttwyrkuosqotxnosypynmncyszwqnutjgrwiacvhpxkzkasyeccndwgivqcryqvnhabqxmevtrvhbrvktbwvehjhomcijmetfwvkiufxlivsrtlincwhxcfxvdtzudvntwgptujsxfarpbcschirbvqanybullkeglpqlwlkbgdpvcckutamtqaaqmaltijafgrdiqqrcjqzalakkslawvafechvyjbshnhdpqhbelkguecpcpcqayregfbrzcvmkzlncuvtqbblnbajihdfaurmslkgxmlhcpcyopgzdbjwnjfgjprtzcxdtbntjtdgzperhtqejdodejqoklgpnixcegximpfmklrvsuoyzwdjoapjroalbgcctorplbzxnmbeprxghmlebosmiqciimcizxmxsxcemwbaivqyqpprpsytoykurnptoapwwwxmxcngilvauocoflnderjzgtsbsmgdpxjtpktocdwapnmorlkdxejlqiieeuhlipdfspbnywvhjhskehjenzcxminfpyvfbuscqitrvvmggotvpdxqpjnwektqrmxhuwvookxxamwqfaglrtsxfamzlmtmfhmkdnnwaeqlmmiacedtiabnhqmasmvqgqqhyokorakgsrbkovggghjxvmmszypwtdxacryttzmntzzhrozpncyomwejjsdvqpnkducrpkvgjddoyfxldpdphvofcqhnsifoequdgbcfaweemyjhuynfmxraloocvtopntieetsarmxxgrueocagfelbhevltedxgicdexxvohqoeigmgswdznjlxfdkxxtdnlhjmwbtvjxdgmvmutrxpsdxadodngwwcmnvkobkxrllevlydqrycevosjehrxiblnanixvfuqibjtldtqhuyepapgkewyhjxtrsgmvybigtgqvqhhodzcpsvawpmckcjnuydcvfabciicqqkqldxgbgerwuxegdeiltjukctwolgspbkgindoibxvtsvfgmievtfzlxyxieerracaopiqvknexevvwqvobzxcqyfiyhcucpvreuuphlmaahhfyijdsszqttpnobzacggifhedlypnrzvkidjilmecrgbjtlelivvysxkmilwkyjyfcogkogigfzmqriqzehdohvjqcfltmatzdbxwygfqmnvklbjlzijmeawrlwmiilhxeiuyabuqhbxljgebeiuxjngvmjvvgmgutgqhjubhdmeurkahmpxyxadpxkdetirtnnjiwylusazcjlvgttxkrklrxroiribihnmaiorreqcaolhhvixkveqzoyiyskamagjfbpvfxnflsgrnykgcpfzhgepaouynjxmifcioqluxwzwpmtjprkesvxuvtnoklwljbpucwzruqhxtvipbjdbsinwxeghxyspnaodgcqkgoatocqqpxqxmwliqngjamryzbayfqbgjtpxoehhtuvtrrtphignupyalifnpflttcdildohkmwtohxckhnwejonlzozbsejdtzfvxkoxsxckbwvdgtcxoregmhahnuptgvsoiyjbmbcgjwjluadppzpqyctnqvwaecrpujxtourfiihvrhmmgrcapyeyndlkysnyyztpihpjyubuhzztzbrlkqnoowzrsumuqkqsigodofwtjyyhrjrinfbzrhbqkbiuyruftsgxvithmbdqwrkktpkpqxbqidaqeydydrdkqiizwkyhuzksfwiwoznnxeciivnfiowgzovtlmgwryxebkfunnbmpzuornqlemqrugzrpvqxykrfvlihxgexlsaipgicgmwqajagmbxdbfkwlxssqlcyuhwzmnzvlspufgkilutcirhlagdmthtjmkbjvbjwyzntfhmkbtpuejwbmymfqbuebhhwkseijlaqaejrmptvtryktsthepxsoofjimjxtacfaxttqhcoiebwytwxwsibeecwhgcjjvoukksphgqptneuqmhvrjewlouephrcnriejanwcjvchteskafqkgmbqxqyzjikslkpzjmaqfhzmkakonpeatytfyyncslnflvivvxclv",
                492_153_482, List.of(23, 20, 4, 11, 4, 24, 13, 25, 12, 21, 17, 7, 6, 21, 12, 11, 22, 25, 22, 16, 19, 8, 16, 18, 19, 16))).isEqualTo(91272833);
    }

    final int MOD = (int) 1e9 + 7;

    public int lengthAfterTransformations(String s, int t, List<Integer> nums) {
        int[][] trans = new int[26][26];

        for (int i = 0; i < 26; i++) {
            int consecutive = nums.get(i);
            for (int j = 1; j <= consecutive; j++) {
                int next = (i + j) % 26;
                trans[next][i] = (trans[next][i] + 1) % MOD;
            }
        }

        int[][] powered = pow(trans, t);

        int[] charCnt = new int[26];
        for (char c : s.toCharArray()) {
            charCnt[c - 'a']++;
        }

        int answer = 0;
        for (int i = 0; i < 26; i++) {
            long sum = 0;
            for (int j = 0; j < 26; j++) {
                sum = (sum + (long) powered[i][j] * charCnt[j]) % MOD;
            }
            answer = (int) ((answer + sum) % MOD);
        }

        return answer;
    }

    private int[][] pow(int[][] mat, int exp) {
        int[][] pow = new int[26][26];
        for (int i = 0; i < 26; i++)
            pow[i][i] = 1;

        while (exp > 0) {
            if ((exp & 1) == 1)
                pow = mul(pow, mat);
            mat = mul(mat, mat);
            exp >>= 1;
        }
        return pow;
    }

    private int[][] mul(int[][] a, int[][] b) {
        int[][] mul = new int[26][26];
        for (int i = 0; i < 26; i++) {
            for (int k = 0; k < 26; k++) {
                if (a[i][k] == 0)
                    continue;
                for (int j = 0; j < 26; j++) {
                    mul[i][j] = (int) ((mul[i][j] + (long) a[i][k] * b[k][j]) % MOD);
                }
            }
        }
        return mul;
    }

}
